/* 小满村 M1 场景数据层
 * 坐标均使用原始背景图坐标：1024 x 682。
 * game.js 只消费这些数据；后续调地图、碰撞、热点优先改这里。
 */
window.XMC_MAPS = window.XMC_MAPS || {};
window.XMC_WORLD = {
  id: 'xiaomancun-world',
  startMap: 'village',
  mapPolicy: {
    villageFreeRoam: '村内户外应是一张连续主地图，院子、村道、邻居家门口、池塘、作坊等只是其中的区域。',
    useSeparateMapWhen: ['进入建筑室内', '去县城', '进山/河滩等远距离区域', '进入剧情副本'],
  },
  maps: {
    village: {
      id: 'village',
      name: '小满村',
      kind: 'outdoor-continuous',
      role: 'main-free-roam',
      targetSize: { width: 1536, height: 1024 },
      areas: [
        { id: 'grandma-yard', name: '外婆家院子', role: 'home-base', approxRect: { x: 30, y: 310, w: 720, h: 520 } },
        { id: 'village-road', name: '村道', role: 'main-path', approxRect: { x: 650, y: 250, w: 520, h: 600 } },
        { id: 'neighbors', name: '邻居屋群', role: 'npc-homes', approxRect: { x: 450, y: 50, w: 980, h: 260 } },
        { id: 'workshop', name: '加工小作坊', role: 'production', approxRect: { x: 760, y: 370, w: 330, h: 210 } },
        { id: 'pond-and-river', name: '池塘河沟', role: 'fishing-water', approxRect: { x: 1000, y: 560, w: 460, h: 360 } },
        { id: 'village-square', name: '晒谷场/小广场', role: 'social-market', approxRect: { x: 720, y: 540, w: 380, h: 240 } },
      ],
      exits: [
        { id: 'to-county', name: '去县城', to: 'county-road', via: '村口大路' },
        { id: 'to-mountain', name: '进山', to: 'mountain-path', via: '竹林小路' },
      ],
    },
    grandmaHouseInterior: {
      id: 'grandma-house-interior',
      name: '外婆家屋内',
      kind: 'interior',
      parentMap: 'village',
    },
    countyRoad: {
      id: 'county-road',
      name: '去县城路',
      kind: 'remote-outdoor',
    },
    mountainPath: {
      id: 'mountain-path',
      name: '后山小路',
      kind: 'remote-outdoor',
    },
  },
};

window.XMC_MAPS.village = {
  id: 'village',
  name: '小满村',
  parentMap: null,
  prototypeRole: '连续户外主地图；外婆家院子只是左下角的 home-base 区域。',
  viewport: { width: 1280, height: 720 },
  imageSize: { width: 1536, height: 1024 },
  assets: {
    baseDir: 'assets/',
    background: 'scenes/village.png',
    characterDir: 'xiaomancun/',
  },
  camera: {
    scale: 1.25,
  },
  player: {
    spawn: { x: 300, y: 590, dir: 'down' },
    speed: 2.4,
    spriteScale: 1.85,
  },
  navigation: {
    pathStep: 16,
    walkBoundary: [
      [38, 368],
      [186, 310],
      [392, 304],
      [580, 226],
      [760, 246],
      [960, 220],
      [1148, 186],
      [1458, 214],
      [1516, 324],
      [1430, 456],
      [1344, 628],
      [1232, 780],
      [1080, 930],
      [884, 1002],
      [598, 968],
      [308, 914],
      [84, 842],
      [20, 654],
    ],
  },
  collision: [
    { id: 'grandma-house', name: '外婆家屋体', shape: 'rect', x: 58, y: 328, w: 322, h: 150 },
    { id: 'home-coop-shed', name: '家园鸡舍棚体', shape: 'rect', x: 42, y: 530, w: 190, h: 104 },
    { id: 'home-stone-table', name: '家园石桌', shape: 'ellipse', cx: 330, cy: 528, rx: 72, ry: 42 },
    { id: 'home-pond', name: '家园池塘', shape: 'ellipse', cx: 580, cy: 554, rx: 124, ry: 66 },
    { id: 'home-field', name: '家园菜地', shape: 'rect', x: 330, y: 620, w: 366, h: 158 },
    { id: 'neighbor-west-house', name: '西侧邻居屋', shape: 'rect', x: 488, y: 78, w: 168, h: 136 },
    { id: 'neighbor-north-house', name: '北侧邻居屋', shape: 'rect', x: 692, y: 58, w: 150, h: 120 },
    { id: 'neighbor-center-house', name: '中部邻居屋', shape: 'rect', x: 922, y: 104, w: 208, h: 142 },
    { id: 'neighbor-east-house', name: '东侧邻居屋', shape: 'rect', x: 1226, y: 96, w: 188, h: 146 },
    { id: 'small-east-house', name: '东侧小屋', shape: 'rect', x: 1370, y: 208, w: 140, h: 112 },
    { id: 'village-workshop', name: '加工小作坊', shape: 'rect', x: 788, y: 394, w: 264, h: 122 },
    { id: 'river-bottom', name: '下方河道', shape: 'ellipse', cx: 992, cy: 862, rx: 382, ry: 84 },
    { id: 'river-east', name: '东侧河沟', shape: 'ellipse', cx: 1398, cy: 610, rx: 94, ry: 222 },
    { id: 'water-mill', name: '水车小屋', shape: 'rect', x: 1180, y: 794, w: 236, h: 150 },
  ],
  hotspots: [
    {
      id: 'grandma-yard',
      name: '外婆家',
      shape: 'rect',
      x: 58,
      y: 320,
      w: 340,
      h: 192,
      stand: { x: 294, y: 590 },
      lines: ['【外婆家院子】', '这里是回乡第一天的起点。', '以后院子只是小满村主地图里的一个家园区域，不再单独占满整个世界。'],
    },
    {
      id: 'field',
      name: '菜地',
      shape: 'rect',
      x: 318,
      y: 610,
      w: 392,
      h: 178,
      stand: { x: 520, y: 820 },
      lines: ['【菜畦】', '家门口这一片菜地连着村道，不是单独关卡。', '（正式版这里接锄地、播种、浇水、施肥、收获。）'],
    },
    {
      id: 'coop',
      name: '鸡舍',
      shape: 'rect',
      x: 36,
      y: 518,
      w: 220,
      h: 172,
      stand: { x: 190, y: 720 },
      lines: ['【鸡舍】', '母鸡们咕咕地刨食。', '鸡舍仍在外婆家区域里，但玩家可以直接走出院子去村里。'],
    },
    {
      id: 'home-pond',
      name: '池塘',
      shape: 'ellipse',
      cx: 580,
      cy: 554,
      rx: 124,
      ry: 66,
      stand: { x: 600, y: 652 },
      lines: ['【院内池塘】', '鸭子在水边慢慢游。', '村外还有河沟和桥，后续可扩展钓鱼点。'],
    },
    {
      id: 'workshop',
      name: '作坊',
      shape: 'rect',
      x: 766,
      y: 372,
      w: 310,
      h: 176,
      stand: { x: 930, y: 560 },
      lines: ['【加工小作坊】', '这里以后能做腌菜、果酱、竹编和订单加工。', '它属于村子主地图，不需要切换关卡。'],
    },
    {
      id: 'neighbors',
      name: '邻居屋群',
      shape: 'rect',
      x: 458,
      y: 58,
      w: 700,
      h: 240,
      stand: { x: 740, y: 306 },
      lines: ['【邻居屋群】', '几户人家的院门沿村道排开。', '后续 NPC 作息会让他们在屋里、门口和广场之间移动。'],
    },
    {
      id: 'square',
      name: '小广场',
      shape: 'rect',
      x: 742,
      y: 548,
      w: 330,
      h: 214,
      stand: { x: 904, y: 732 },
      lines: ['【晒谷场】', '村里碰头、摆摊、晒谷子的地方。', '这里适合做每日任务、集市和节日入口。'],
    },
    {
      id: 'bridge',
      name: '石桥',
      shape: 'rect',
      x: 1130,
      y: 608,
      w: 212,
      h: 132,
      stand: { x: 1210, y: 720 },
      lines: ['【石桥】', '过桥还能继续沿河走。', '远处区域可以接后山、河滩或县城路。'],
    },
    {
      id: 'county-road',
      name: '去县城',
      shape: 'rect',
      x: 1340,
      y: 214,
      w: 180,
      h: 142,
      stand: { x: 1390, y: 374 },
      lines: ['【村口大路】', '再往外才是去县城的路。', '这里才应该切到新的远距离地图。'],
    },
  ],
  effects: {
    pondShimmer: { x: 580, y: 554 },
    petals: {
      x: 520,
      yMin: 70,
      yMax: 700,
      width: 860,
      resetLeft: 420,
      resetBelow: 820,
    },
  },
  dialogue: {
    intro: [
      '哎哟，回来啦！外婆盼你好些天咯。',
      '这回先不把院子当成整个世界了——沿着村道走，作坊、邻居屋、小广场都在外头。',
      '先在小满村里转一圈，熟熟路。',
    ],
  },
};

window.XMC_MAPS.courtyard = {
  id: 'courtyard',
  name: '外婆家小院',
  parentMap: 'village',
  parentArea: 'grandma-yard',
  prototypeRole: '当前可玩切片；正式版应并入小满村连续户外主地图。',
  viewport: { width: 1280, height: 720 },
  imageSize: { width: 1024, height: 682 },
  assets: {
    baseDir: 'assets/',
    background: 'scenes/courtyard.png',
    characterDir: 'xiaomancun/',
  },
  player: {
    spawn: { x: 360, y: 300, dir: 'down' },
    speed: 2.4,
    spriteScale: 1.85,
  },
  navigation: {
    pathStep: 16,
    walkBoundary: [
      [150, 250],
      [300, 246],
      [470, 250],
      [565, 250],
      [660, 268],
      [822, 286],
      [836, 455],
      [720, 555],
      [380, 578],
      [248, 560],
      [150, 470],
      [108, 360],
    ],
  },
  collision: [
    { id: 'coop-shed', name: '鸡舍棚体', shape: 'rect', x: 125, y: 296, w: 122, h: 86 },
    { id: 'stone-table', name: '石桌凳', shape: 'ellipse', cx: 326, cy: 347, rx: 58, ry: 32 },
    { id: 'well', name: '水井', shape: 'ellipse', cx: 490, cy: 347, rx: 40, ry: 34 },
    { id: 'pond', name: '池塘', shape: 'ellipse', cx: 732, cy: 332, rx: 104, ry: 64 },
    { id: 'vegetable-beds', name: '菜地', shape: 'rect', x: 340, y: 414, w: 344, h: 114 },
    { id: 'tool-shed', name: '工具棚', shape: 'rect', x: 690, y: 496, w: 196, h: 116 },
  ],
  hotspots: [
    {
      id: 'field',
      name: '菜地',
      shape: 'rect',
      x: 318,
      y: 394,
      w: 386,
      h: 134,
      stand: { x: 510, y: 556 },
      lines: ['【菜畦】', '白菜、青苗、豆架，长得正欢。', '（正式版这里能锄地、播种、浇水、施肥、看成熟倒计时、收获。）'],
    },
    {
      id: 'pond',
      name: '池塘',
      shape: 'ellipse',
      cx: 732,
      cy: 332,
      rx: 104,
      ry: 64,
      stand: { x: 732, y: 420 },
      lines: ['【池塘】', '几只鸭子在打盹儿，水面荡着圈圈。', '（正式版可钓鱼、养鸭、捡鸭蛋。）'],
    },
    {
      id: 'coop',
      name: '鸡舍',
      shape: 'rect',
      x: 115,
      y: 296,
      w: 142,
      h: 150,
      stand: { x: 205, y: 475 },
      lines: ['【鸡舍】', '母鸡们咕咕地刨食。', '（正式版可喂鸡、捡蛋、孵小鸡。）'],
    },
    {
      id: 'house-door',
      name: '屋门',
      shape: 'rect',
      x: 266,
      y: 172,
      w: 84,
      h: 80,
      stand: { x: 305, y: 266 },
      lines: ['【老屋】', '门上还贴着褪色的春联。', '（屋内场景待绘制，先在院里逛逛吧。）'],
    },
    {
      id: 'yard-gate',
      name: '院门',
      shape: 'rect',
      x: 236,
      y: 504,
      w: 124,
      h: 96,
      stand: { x: 300, y: 522 },
      lines: ['【院门】', '推开就是村道。', '（村道 / 县城场景待做。）'],
    },
    {
      id: 'stone-table',
      name: '石桌',
      shape: 'ellipse',
      cx: 322,
      cy: 347,
      rx: 80,
      ry: 47,
      stand: { x: 322, y: 412 },
      lines: ['【石桌】', '坐下歇会儿，喝口粗茶。', '回乡头一天，先把院子重新逛熟。'],
    },
  ],
  effects: {
    pondShimmer: { x: 732, y: 332 },
    petals: {
      x: 600,
      yMin: 40,
      yMax: 420,
      width: 250,
      resetLeft: 540,
      resetBelow: 440,
    },
  },
  dialogue: {
    intro: [
      '哎哟，回来啦！外婆盼你好些天咯。',
      '院子你随便逛——点地面走路，点菜地、池塘、鸡舍、屋门看看。',
      '慢慢来，把这院子重新过成日子。',
    ],
  },
};
