/* 小满村 M1 地图数据层
 *
 * 这版开始改成“星露谷式”的运行结构：
 * - 地面是瓦片层；
 * - 房子、鸡舍、树、栅栏、井等是对象层；
 * - 主角、村民、鸡是实体层；
 * - 作物是植物状态层；
 * - 碰撞、交互、传送点都来自数据，而不是一张画死的背景图。
 */
window.XMC_MAPS = window.XMC_MAPS || {};

window.XMC_WORLD = {
  id: 'xiaomancun-world',
  startMap: 'village',
  mapPolicy: {
    villageFreeRoam: '村内户外是一张连续主地图，院子、田地、鸡舍、邻居家、作坊、池塘、村口只是不同区域。',
    useSeparateMapWhen: ['进入建筑室内', '去县城', '进山/河滩等远距离区域', '进入剧情副本'],
  },
  maps: {
    village: {
      id: 'village',
      name: '小满村',
      kind: 'outdoor-continuous',
      role: 'main-free-roam',
    },
    grandmaHouseInterior: {
      id: 'grandma-house-interior',
      name: '外婆家屋内',
      kind: 'interior',
      parentMap: 'village',
    },
    countyRoad: {
      id: 'county-road',
      name: '去县城路',
      kind: 'remote-outdoor',
    },
  },
};

window.XMC_MAPS.village = {
  id: 'village',
  name: '小满村',
  engine: 'layered-tilemap',
  viewport: { width: 1280, height: 720 },
  tileSize: 16,
  renderScale: 2,
  width: 80,
  height: 52,
  assets: {
    baseDir: 'assets/',
    characterDir: 'xiaomancun/',
    animalDir: 'xiaomancun/',
    sources: {
      grass: 'xiaomancun/grass_sheet.png',
      tilled: 'xiaomancun/tilled_sheet.png',
      water: 'xiaomancun/water_sheet.png',
      plants: 'xiaomancun/plants_sheet.png',
      house: 'xiaomancun/house.png',
      chickenHouse: 'xiaomancun/chicken_house.png',
      eggItem: 'xiaomancun/egg_item.png',
      fence: 'sprout/fences_sheet.png',
    },
    referenceScene: 'scenes/village.png',
  },
  tiles: {
    grassA: { source: 'grass', sx: 0, sy: 0, w: 16, h: 16 },
    grassB: { source: 'grass', sx: 16, sy: 0, w: 16, h: 16 },
    grassC: { source: 'grass', sx: 32, sy: 0, w: 16, h: 16 },
    grassFlower: { source: 'grass', sx: 80, sy: 0, w: 16, h: 16 },
    tilledA: { source: 'tilled', sx: 0, sy: 0, w: 16, h: 16 },
    tilledB: { source: 'tilled', sx: 16, sy: 0, w: 16, h: 16 },
    waterA: { source: 'water', sx: 0, sy: 0, w: 16, h: 16, blocks: true },
    waterB: { source: 'water', sx: 16, sy: 0, w: 16, h: 16, blocks: true },
    waterC: { source: 'water', sx: 32, sy: 0, w: 16, h: 16, blocks: true },
    path: { fill: '#c99a5e', speckles: ['#b98145', '#dfb477', '#9f6b36'] },
    stone: { fill: '#a89d86', speckles: ['#8c806d', '#c4b9a2', '#766b5b'] },
  },
  cropTypes: {
    bokchoy: { name: '小白菜', maxStage: 3, value: 8, spriteOffset: 0 },
    radish: { name: '萝卜', maxStage: 3, value: 10, spriteOffset: 1 },
    herb: { name: '香草', maxStage: 3, value: 6, spriteOffset: 2 },
  },
  terrain: {
    base: 'grassA',
    detailTiles: ['grassA', 'grassB', 'grassC', 'grassFlower'],
    patches: [
      { id: 'home-path', tile: 'path', x: 9, y: 11, w: 4, h: 21 },
      { id: 'main-road', tile: 'path', x: 10, y: 14, w: 61, h: 4 },
      { id: 'field-road', tile: 'path', x: 12, y: 32, w: 55, h: 4 },
      { id: 'north-road', tile: 'path', x: 41, y: 8, w: 4, h: 25 },
      { id: 'east-road', tile: 'path', x: 68, y: 11, w: 5, h: 34 },
      { id: 'square', tile: 'stone', x: 43, y: 18, w: 14, h: 9 },
      { id: 'home-field', tile: 'tilledA', x: 20, y: 27, w: 13, h: 7 },
      { id: 'east-field', tile: 'tilledB', x: 35, y: 27, w: 11, h: 7 },
      { id: 'workshop-field', tile: 'tilledA', x: 53, y: 24, w: 8, h: 6 },
      { id: 'pond', tile: 'waterA', x: 54, y: 33, w: 11, h: 7, blocks: true },
      { id: 'river', tile: 'waterB', x: 70, y: 24, w: 6, h: 24, blocks: true },
    ],
  },
  areas: [
    { id: 'grandma-yard', name: '外婆家院子', x: 3, y: 4, w: 22, h: 31 },
    { id: 'home-field', name: '家门口田地', x: 19, y: 26, w: 28, h: 10 },
    { id: 'village-road', name: '村道', x: 10, y: 11, w: 63, h: 26 },
    { id: 'neighbors', name: '邻居屋群', x: 24, y: 4, w: 48, h: 11 },
    { id: 'workshop', name: '加工小作坊', x: 43, y: 6, w: 15, h: 15 },
    { id: 'pond', name: '池塘河沟', x: 53, y: 31, w: 23, h: 18 },
  ],
  player: {
    spawn: { x: 10.5, y: 13.5, dir: 'down' },
    speed: 1.55,
    spriteScale: 1,
  },
  navigation: {
    pathStep: 8,
    walkableAreas: [
      { id: 'village-playable', name: '村内可活动范围', x: 2, y: 3, w: 76, h: 47 },
      { id: 'county-road-mouth', name: '村口大路入口', x: 68, y: 10, w: 8, h: 10 },
    ],
    blockedAreas: [
      { id: 'north-woods-edge', name: '北侧树墙', x: 0, y: 0, w: 80, h: 3 },
      { id: 'west-bamboo-edge', name: '西侧竹林', x: 0, y: 0, w: 2, h: 52 },
      { id: 'south-village-edge', name: '南侧村界', x: 0, y: 50, w: 80, h: 2 },
      { id: 'east-river-edge', name: '东侧河岸外', x: 76, y: 0, w: 4, h: 52 },
    ],
    passableAreas: [
      { id: 'home-yard-gate', name: '院门缺口', x: 22.6, y: 12, w: 1.8, h: 6 },
      { id: 'coop-yard-gate', name: '鸡舍门口', x: 10, y: 27, w: 3, h: 4 },
    ],
  },
  animalAreas: [
    {
      id: 'coop-yard',
      name: '鸡舍活动区',
      rect: { x: 5.4, y: 26.6, w: 10.6, h: 3.6 },
      home: { x: 7.4, y: 27.5 },
      water: { x: 10.2, y: 28.7 },
      behavior: {
        roamWait: [45, 135],
        roamSpeed: 0.32,
        sleepFrom: 1080,
      },
    },
  ],
  objects: [
    {
      id: 'grandma-house',
      kind: 'sprite',
      sprite: 'house',
      name: '外婆家',
      x: 5,
      y: 5,
      w: 7,
      h: 5,
      collision: [{ x: 5, y: 8.2, w: 7, h: 1.8 }],
      interact: {
        name: '屋门',
        rect: { x: 7.2, y: 8.8, w: 2.8, h: 2.8 },
        stand: { x: 8.5, y: 12.1 },
        action: { type: 'sleep', label: '睡觉' },
        lines: ['【外婆家】', '屋里还留着旧木柜和灶台的味道。', '正式版这里会切到屋内地图。'],
      },
    },
    {
      id: 'coop',
      kind: 'sprite',
      sprite: 'chickenHouse',
      name: '鸡舍',
      x: 5,
      y: 23,
      w: 5,
      h: 4,
      collision: [{ x: 5, y: 25.3, w: 5, h: 1.7 }],
      interact: {
        name: '鸡舍',
        rect: { x: 4.5, y: 22.6, w: 6, h: 5.4 },
        stand: { x: 10.7, y: 28.8 },
        lines: ['【鸡舍】', '鸡舍是独立对象，不再画死在背景里。', '以后喂食、产蛋、回窝都会挂在鸡和鸡舍的数据上。'],
      },
    },
    {
      id: 'neighbor-west',
      kind: 'sprite',
      sprite: 'house',
      name: '阿田家',
      x: 25,
      y: 5,
      w: 7,
      h: 5,
      collision: [{ x: 25, y: 8.2, w: 7, h: 1.8 }],
      interact: {
        name: '阿田家',
        rect: { x: 27.3, y: 8.8, w: 2.7, h: 2.8 },
        stand: { x: 28.5, y: 12 },
        lines: ['【阿田家】', '院门半掩着，里面传来剁菜声。', '这里会接村民作息和拜访逻辑。'],
      },
    },
    {
      id: 'workshop',
      kind: 'sprite',
      sprite: 'house',
      name: '加工小作坊',
      x: 46,
      y: 7,
      w: 7,
      h: 5,
      collision: [{ x: 46, y: 10.2, w: 7, h: 1.8 }],
      interact: {
        name: '作坊',
        rect: { x: 48.2, y: 10.6, w: 3, h: 3 },
        stand: { x: 49.7, y: 14.4 },
        lines: ['【加工小作坊】', '这里以后做腌菜、果酱和竹编订单。', '作坊是村子主地图里的建筑对象。'],
      },
    },
    {
      id: 'neighbor-east',
      kind: 'sprite',
      sprite: 'house',
      name: '桂嫂家',
      x: 61,
      y: 7,
      w: 7,
      h: 5,
      collision: [{ x: 61, y: 10.2, w: 7, h: 1.8 }],
      interact: {
        name: '桂嫂家',
        rect: { x: 63.2, y: 10.6, w: 3, h: 3 },
        stand: { x: 64.7, y: 14.4 },
        lines: ['【桂嫂家】', '门口晾着竹篮，屋后是一排菜垄。', '后续 NPC 会按时间在家、村道、广场间移动。'],
      },
    },
    { id: 'home-yard-fence-n', kind: 'fence', name: '院墙栅栏', x: 3, y: 4, w: 21, h: 1, collision: [{ x: 3, y: 4, w: 21, h: 0.8 }] },
    { id: 'home-yard-fence-w', kind: 'fence', name: '院墙栅栏', x: 3, y: 4, w: 1, h: 25, collision: [{ x: 3, y: 4, w: 0.8, h: 25 }] },
    { id: 'home-yard-fence-e-top', kind: 'fence', name: '院墙栅栏', x: 23, y: 4, w: 1, h: 8, collision: [{ x: 23, y: 4, w: 0.8, h: 8 }] },
    { id: 'home-yard-fence-e-bottom', kind: 'fence', name: '院墙栅栏', x: 23, y: 18, w: 1, h: 6, collision: [{ x: 23, y: 18, w: 0.8, h: 6 }] },
    { id: 'coop-fence-s', kind: 'fence', name: '鸡舍围栏', x: 4, y: 30, w: 13, h: 1, collision: [{ x: 4, y: 30, w: 13, h: 0.8 }] },
    { id: 'coop-fence-w', kind: 'fence', name: '鸡舍围栏', x: 4, y: 22, w: 1, h: 9, collision: [{ x: 4, y: 22, w: 0.8, h: 9 }] },
    { id: 'field-fence-n', kind: 'fence', name: '田边竹篱', x: 19, y: 26, w: 28, h: 1, collision: [{ x: 19, y: 26, w: 28, h: 0.7 }] },
    { id: 'well', kind: 'well', name: '水井', x: 38, y: 19, w: 2, h: 2, collision: [{ x: 38.2, y: 19.4, w: 1.6, h: 1.4 }], interact: { name: '水井', rect: { x: 37.6, y: 18.8, w: 3, h: 3 }, stand: { x: 37, y: 21.5 }, lines: ['【水井】', '井水很凉，桶沿被磨得发亮。', '后续浇水会从这里或水塘取水。'] } },
    { id: 'notice-board', kind: 'sign', name: '村务牌', x: 43, y: 22, w: 2, h: 2, collision: [{ x: 43.2, y: 22.4, w: 1.6, h: 1.4 }], interact: { name: '村务牌', rect: { x: 42.7, y: 21.7, w: 3, h: 3 }, stand: { x: 42.3, y: 24.4 }, lines: ['【村务牌】', '今日：熟悉小满村，认识邻居。', '这里以后挂每日委托和节日公告。'] } },
    { id: 'peach-tree-home', kind: 'tree', name: '桃树', x: 15, y: 7, w: 4, h: 5, collision: [{ x: 16, y: 10.8, w: 1.8, h: 1.8 }] },
    { id: 'bamboo-clump', kind: 'tree', name: '竹丛', x: 1, y: 13, w: 4, h: 7, collision: [{ x: 2, y: 17.8, w: 1.8, h: 2 }] },
    { id: 'road-tree', kind: 'tree', name: '槐树', x: 58, y: 16, w: 4, h: 5, collision: [{ x: 59, y: 19.8, w: 1.8, h: 1.8 }] },
    { id: 'pond-willow', kind: 'tree', name: '柳树', x: 64, y: 31, w: 5, h: 6, collision: [{ x: 66, y: 35.8, w: 1.8, h: 1.8 }] },
  ],
  cropBeds: [
    {
      id: 'home-vegetables',
      name: '家门口菜地',
      rect: { x: 20, y: 27, w: 13, h: 7 },
      stand: { x: 26.5, y: 35.5 },
      owner: 'player',
      crop: 'bokchoy',
      stagePattern: [1, 2, 3, 2, 1, 3],
      wateredPattern: [false, true, false, false, true],
      lines: ['【家门口菜地】', '作物是一格一格的数据，不是背景贴图。', '靠近后可以浇水或收获成熟的小白菜。'],
    },
    {
      id: 'east-vegetables',
      name: '邻家菜地',
      rect: { x: 35, y: 27, w: 11, h: 7 },
      stand: { x: 40.5, y: 35.5 },
      owner: 'neighbor',
      crop: 'radish',
      stagePattern: [2, 3, 1, 2, 3],
      lines: ['【邻家菜地】', '这里以后会属于村民，玩家不能随便收。', '地块所有权也应该进地图数据。'],
    },
    {
      id: 'workshop-herbs',
      name: '作坊香草畦',
      rect: { x: 53, y: 24, w: 8, h: 6 },
      stand: { x: 57, y: 31.5 },
      owner: 'workshop',
      crop: 'herb',
      stagePattern: [1, 1, 2, 3],
      lines: ['【香草畦】', '作坊旁边种着薄荷和紫苏。', '加工配方可以从这些植物状态读取材料。'],
    },
  ],
  entities: [
    {
      id: 'grandma',
      type: 'npc',
      name: '外婆',
      x: 14.2,
      y: 13.3,
      dir: 'down',
      spriteSet: 'farmer',
      schedule: [
        { from: 360, to: 540, x: 14.2, y: 13.3, dir: 'down', activity: '在院子里等你熟悉环境' },
        { from: 540, to: 720, x: 25.8, y: 35.2, dir: 'up', activity: '在家门口菜地看苗' },
        { from: 720, to: 1080, x: 43.8, y: 24.8, dir: 'down', activity: '去村务牌旁和邻居说话' },
        { from: 1080, to: 1440, x: 8.5, y: 12.1, dir: 'down', activity: '傍晚回屋准备晚饭' },
      ],
      dialogue: ['【外婆】', '村子不是一张画，得让人、鸡、菜、树都各过各的日子。', '你先把路走熟，别着急。'],
    },
    {
      id: 'workshop-owner',
      type: 'npc',
      name: '阿木叔',
      x: 53.8,
      y: 15.2,
      dir: 'left',
      spriteSet: 'farmer',
      schedule: [
        { from: 360, to: 600, x: 53.8, y: 15.2, dir: 'left', activity: '在作坊门口清点工具' },
        { from: 600, to: 1020, x: 49.6, y: 23.6, dir: 'down', activity: '在广场边收村民订单' },
        { from: 1020, to: 1440, x: 53.4, y: 14.3, dir: 'left', activity: '回作坊收工' },
      ],
      dialogue: ['【阿木叔】', '作坊早上开门，傍晚收工。', '后续我会按日程在作坊、广场、家之间走。'],
    },
    {
      id: 'neighbor-atan',
      type: 'npc',
      name: '阿田',
      x: 28.7,
      y: 13.5,
      dir: 'down',
      spriteSet: 'farmer',
      schedule: [
        { from: 360, to: 660, x: 28.7, y: 13.5, dir: 'down', activity: '在自家门口整理种子' },
        { from: 660, to: 1080, x: 40.4, y: 35.4, dir: 'up', activity: '在邻家菜地照看萝卜' },
        { from: 1080, to: 1440, x: 28.5, y: 12, dir: 'down', activity: '回家收拾农具' },
      ],
      dialogue: ['【阿田】', '我家的菜地在东边，别急，等关系熟了再教你换种子。', '村民的地块和你自己的地块要分开算。'],
    },
    {
      id: 'neighbor-guisao',
      type: 'npc',
      name: '桂嫂',
      x: 64.5,
      y: 15.2,
      dir: 'left',
      spriteSet: 'farmer',
      schedule: [
        { from: 360, to: 720, x: 64.5, y: 15.2, dir: 'left', activity: '在桂嫂家门口编竹篮' },
        { from: 720, to: 1080, x: 57.6, y: 31.4, dir: 'up', activity: '去香草畦旁摘叶子' },
        { from: 1080, to: 1440, x: 64.7, y: 14.4, dir: 'left', activity: '傍晚回家晾竹篾' },
      ],
      dialogue: ['【桂嫂】', '香草畦归作坊用，做腌菜、香包都少不了。', '你自己的菜地先顾好，别把全村的菜都薅了。'],
    },
    {
      id: 'chicken-a',
      type: 'animal',
      species: 'chicken',
      name: '小黄',
      x: 8,
      y: 28,
      fed: false,
      eggReady: false,
      activityArea: 'coop-yard',
      dialogue: ['【小黄】', '咕咕。'],
    },
    {
      id: 'chicken-b',
      type: 'animal',
      species: 'chicken',
      name: '小白',
      x: 12,
      y: 28.5,
      fed: false,
      eggReady: true,
      activityArea: 'coop-yard',
      dialogue: ['【小白】', '咕？'],
    },
    {
      id: 'chicken-c',
      type: 'animal',
      species: 'chicken',
      name: '花花',
      x: 14.5,
      y: 29,
      fed: false,
      eggReady: false,
      activityArea: 'coop-yard',
      dialogue: ['【花花】', '它低头啄了啄地。'],
    },
  ],
  portals: [
    {
      id: 'to-county-road',
      name: '村口大路',
      rect: { x: 70, y: 11, w: 6, h: 7 },
      stand: { x: 69.5, y: 16 },
      lines: ['【村口大路】', '再往外才应该切去县城或大地图。', '村子内部先保持连续自由移动。'],
    },
  ],
  effects: {
    petals: { x: 15, y: 6, w: 52, h: 32 },
    water: [{ x: 54, y: 33, w: 11, h: 7 }, { x: 70, y: 24, w: 6, h: 24 }],
  },
  dialogue: {
    intro: [
      '哎哟，回来啦！外婆盼你好些天咯。',
      '这次咱不把一张大图当世界了：路、屋、鸡、菜、树都拆开跑。',
      '你先在村里走一圈，看看田地、鸡舍、作坊和村口。',
    ],
  },
};
